title: "Camille Hall"
email: camihall2@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I am a student studying computer science.
baseurl: "/" 
url: "/camihall" 
twitter_username: Camille_H
github_username:  camihall

sass:
  sass_dir: _sass

icon: ./assets/img/smol.jpg
